<?php
/**
 * Created by PhpStorm.
 * User: weichen
 * Date: 2019/2/26
 * Time: 11:52
 */
namespace app\http\exception;

use Exception;
use think\exception\Handle;

/**
 * 自定义错误处理
 * Class MyHandle
 * @package app\http\exception
 */
class MyHandle extends Handle
{
    /**
     * 重写render 返回json数据
     * @param Exception $e
     * @return \think\Response
     */
    public function render(Exception $e)
    {
        //自定义的异常 则不需要显示完整的信息
        if ($e instanceof MyException) {
        } else {
            //开启debug的时候显示完整的错误信息
            if (config('app.app_debug')) {
                return parent::render($e); // TODO: Change the autogenerated stub
            }
        }

        //返回json的格式
        return json([
            'code' => $e->getCode(),
            'message' => $e->getMessage(),
            'data' => null
        ]);
    }
}